### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by yashLadha** [vitorfs/bootcamp#101]
We can develop a rest api for the current codebase extending it's all functionalities. So that it can be used across several platforms.

**Comment by sebastian-code** [comment]
I have been thinking about this, but until now I haven't been able to find a probable use case for the project, do you mind elaborating about the idea and the use case?

**Comment by yashLadha** [comment]
Extending the app to mobile platform.

**Comment by sebastian-code** [comment]
Interesting, let's take a look and work on it. This looks promising.

**Comment by congtoanle** [comment]
I am building Rest Framework API using for VueJs. If @yashLadha want develop with me, could you add my skype or Facebook?

**Comment by yashLadha** [comment]
Yaa sure. Send me ur facebook link and skype name?
My Skype Name is : Yash Ladha

**Comment by sebastian-code** [comment]
This looks interesting. I would like to see that vue.js UI.

**Comment by chetanya-shrimali** [comment]
Hey I am chetanya. I would like to work on this issue. Even Flask is a good Framework to build an API on @yashLadha @sebastian-code . I have created some API and secured endpoints in it. I can direct you to the Github project link!!

**Comment by sebastian-code** [comment]
This sounds interesting @chetanya-shrimali. We are open to this. Please feel free to submit your PR, or in any case try to contact @yashLadha and @congtoanle to check if you can work together.

All of you, let me know if there is something I can do to help.

**Comment by yashLadha** [comment]
It is in Django, the current codebase so we can use the DRF(Django Rest
Framework) also as it will not make a separate code and can be used with
the current codebase. @chetanya-shrimali @congtoanle Views?

**Comment by chetanya-shrimali** [comment]
@sebastian-code i already contacted @yashLadha as we are roommates :p

**Comment by chetanya-shrimali** [comment]
@yashLadha fair enough. We can directly create it via Django Rest Framework instead of switching codebase.

**Comment by sebastian-code** [comment]
Have you tried Python Graphene for API?

**Comment by chetanya-shrimali** [comment]
I haven't before. But just saw the documentation it provides variety of integrations. Seems interesting!!

**Comment by sebastian-code** [comment]
Yes, I haven't tried, but I think than perhaps it would be useful or at least interesting. Anyway, feel free to submit the resulting PR; don't forget to add the proper tests for the new code, and do it against the develop branch.

**Comment by chetanya-shrimali** [comment]
Fine i'll explore the it!!

**Comment by sinhapiyush86** [comment]
Hello, people, I am completely new to open source world, Can anyone help me to sort out how can I help in this project? I have some experience in working with Django rest framework. This is the link(https://temperatureapi.herokuapp.com/temperature) to my hobby project which is a RestAPI and it records temperature from an android application embedded with Arduino.Can someone help me entering in open source world?

**Comment by sebastian-code** [comment]
That's a really though question @sinhapiyush86 but somehow is similar to work with a remote team, perhaps the aim of the project is different.

To be sincere, I'm not the best person to ask, but perhaps [this content](https://opensource.guide/how-to-contribute/) can help a little bit.

**Comment by sinhapiyush86** [comment]
Thanks @sebastian-code

**Comment by 007akk** [comment]
@sebastian-code  Hi sebastian , I went through ur site , and i really found i pleasing , i am a newbie to working with django and rest framework , but i really find all this stuff interesting , I really want to do contribute in this project , let me know if there is something i can contribute

**Comment by ijajmulani** [comment]
Hi Guys, I also wan't to contribute in this feature. Let me know where do I start.

**Comment by sebastian-code** [comment]
Went for a different approach using GraphQL to solve it.
