### ISSUE TITLE
add Python 3 support

### ISSUE THREAD

**Issue by bauripalash** [vitorfs/bootcamp#104]
You're only supporting Python 2 but I can't use it in Python 3. That is causing a huge problem to me.

**Comment by sebastian-code** [comment]
Hi @bauripalash Can you explain this better? Right now Bootcamp is written for Python3 and has some additions to support Python 2, so I don't understand what you're talking about.

**Comment by bauripalash** [comment]
It seems like, everything i heard about Bootcamp, that it's written for
Python 2 , is wrong.
I'm sorry for wasting your valuable time.

**Comment by sebastian-code** [comment]
Is never a waste of time, and is always a pleasure to be of some help; as you read in the **Technology Stack** on the README file in the main repo page, it actually runs on both.

To be truthful, originally the software was written for Python 2, but I ported the code and added the necessary code to keep the software backwards compatible. Bootcamp actually runs on Python 2 if you want to use it that way, but now is meant to be run on Python 3.

Just a question out of curiosity, you said "_everything i heard about Bootcamp..._", to what do you refer? What you have heard of it?

**Comment by bauripalash** [comment]
I heard in some forums ( I don't remember their names ) that BootCamp is
good way to build my own social networking sites, and it's written for only
Python 2.

Actually I am a 15 year old programmer from India and I want a build a
social platform where people can share their knowledge with world.
On Aug 20, 2017 7:16 PM, "Sebastian Reyes Espinosa" <
notifications@github.com> wrote:

Is never a waste of time, and is always a pleasure to be of some help; as
you read in the *Technology Stack* on the README file in the main repo
page, it actually runs on both.

To be truthful, originally the software was written for Python 2, but I
ported the code and added the necessary code to keep the software backwards
compatible. Bootcamp actually runs on Python 2 if you want to use it that
way, but now is meant to be run on Python 3.

Just a question out of curiosity, you said "*everything i heard about
Bootcamp...*", to what do you refer? What you have heard of it?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/vitorfs/bootcamp/issues/104#issuecomment-323585960>,
or mute
the thread

**Comment by sebastian-code** [comment]
I think is actually great what you are saying, and thank for taking the time to explain it to me. Is curious how the software has evolved.

AS you may have noticed, this software is OSS so you are free to use it, adapt it, and if if you feel like it, you also can contribute to it. It would be great if you can create a great software using it as your foundation.

**Comment by bauripalash** [comment]
Thank you 🙂🙂 for clearing my doubts
