### ISSUE TITLE
hello ! how can i use bootcamp in mysql ?

### ISSUE THREAD

**Issue by zoearthmoon** [vitorfs/bootcamp#108]
hello ! how can i use bootcamp in mysql ?

i want to use this project in mysql database
but i dont know how to change or config it
can some one teach me ?

thanks!

https://github.com/vitorfs/bootcamp/wiki/Installing-and-Running-Bootcamp

**Comment by sebastian-code** [comment]
Hi, when you set up the `.env` file, change the PostgreSQL URL configuration line for one of the likes of MySQL; you need to consider than the actual Docker configuration is not compatible with this database, you'll have to override the docker-compose setup file by yourself if you want to use it.

This line is an example line to set up the connection `mysql://USER:PASSWORD@HOST:PORT/NAME` where you'll have to provide the environment variables required.
