### ISSUE TITLE
Splitting Comment and Feeds

### ISSUE THREAD

**Issue by congtoanle** [vitorfs/bootcamp#111]
According to structure of Bootcamp, Feeds structure is: Feed (Parent Feed) - Comment (Child Feed). How about separating it into two database table and make a connection between them
Like this Database Structure: https://i.stack.imgur.com/98wSu.png, **Posts** and **PostComments** is made two database table separately.

**Comment by sebastian-code** [comment]
How this would benefit the user base? How would this improve the software? Do you have a feature in mind which requires something of the likes?

**Comment by sebastian-code** [comment]
Hi @congtoanle do you have some update on this?

**Comment by sebastian-code** [comment]
Closing until further development is available.
