### ISSUE TITLE
django admin page not found

### ISSUE THREAD

**Issue by teenoh** [vitorfs/bootcamp#112]
I can't seem to open django admin page. 
I have included `url(r'^admin/', admin.site.urls),` in bootcamp.urls but I keep getting an error that admin/index.html is not found when I try to open it.

**Comment by sebastian-code** [comment]
The django admin panel is not enabled by default, for that please check the Django documentation on how to enable and configure it.

**Comment by teenoh** [comment]
Ouch!! just saw that, Thanks for the hindsight. It's working now
