### ISSUE TITLE
Why this project use less get_object_or_404 than objects.get, What's the benefits?

### ISSUE THREAD

**Issue by rthel** [vitorfs/bootcamp#114]
I'm new to Django, in my view the former is more convenient and can quick response to the wrong request, anybody knows the difference between these two method? does these two method have different CPU expenses?  : )

**Comment by vitorfs** [comment]
Hey @rthel :-)

The `get_object_or_404` is just a shortcut for

```python
try:
    obj = Model.objects.get(pk=pk)
except Model.DoesNotExist:
    raise Http404
```

I guess the difference (in terms of performance) is negligible. It really depends on what you are trying to achieve

**Comment by sebastian-code** [comment]
Hi @rthel Like @vitorfs says, and perhaps the documentation can help you understand about that a little bit more [here](https://docs.djangoproject.com/en/1.11/topics/http/shortcuts/#get-object-or-404)
