### ISSUE TITLE
When an article is too long, articles list page will look like too mess and complex

### ISSUE THREAD

**Issue by rthel** [vitorfs/bootcamp#116]
I think we can make some change in template to solve long article problem. Django built-in template filters support `truncatewords` to truncates a string after a certain number of words, `striptags` to  strip all HTML tags. how about use this two filter to slice the article content.

Template `articles.html`:
```
{% include "articles/partial_article.html" with article=article briefmode="on" %}
```
Template `partial_article.html`:
```
<div class="content">
    {% if briefmode == 'on' %}
    {{ article.get_content_as_markdown | striptags | truncatewords:140 }}
    {% else %}
    {{ article.get_content_as_markdown| safe }}
    {% endif %}
</div>
```

> `truncatewords` seem not working  well in Non Indo European languages family like Chinese and Japanese : (

**Comment by sebastian-code** [comment]
Hi @rthel, the issue is with the actual markdown implementation and this is related to #92; if you add a big image o have a really long word, it will be shown going over the margins, and this happens to every single app in Bootcamp working with markdown.

Ont the `truncatewords` filter tag, you need to have in consideration than at this point that template is already showing only 255 characters because is used while calling the method `get_summary_as_markdown()` for its context.

**Comment by WUJISHANXIA** [comment]
Hi @sebastian-code , here is my solution. 1.translate markdown to html 2.get  summary from the html by using HTMLParser. this can filter the image.
```
def get_summary_as_markdown(self):
    markdown_html = markdown.markdown(self.get_summary(), safe_mode='escape')
    html_parser = SummaryHTMLParser()
    html_parser.feed(markdown_html)
    return html_parser.get_summary()
```
Class `SummaryHTMLParser`
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Get a raw summary of the HTML-format document"""
from HTMLParser import HTMLParser
class SummaryHTMLParser(HTMLParser):
    def __init__(self):
        HTMLParser.__init__(self)
        self.summary = u''
    def feed(self, data):
        assert(isinstance(data, unicode))
        HTMLParser.feed(self, data)
    def handle_data(self, data):
            self.summary +=' '+data
    def get_summary(self, suffix=u''):
        return u'{0}{1}'.format(self.summary, suffix)
```
example:
this article has big image
![2017-10-03 10 55 27](https://user-images.githubusercontent.com/13394577/31131928-1ea72134-a821-11e7-88e5-24d38070e60a.png)

 it is  working properly
![2017-10-03 10 44 37](https://user-images.githubusercontent.com/13394577/31131362-8e01197e-a81f-11e7-829d-1517f7cd6904.png)

**Comment by sebastian-code** [comment]
Great solution @WUJISHANXIA How does it works with really long strings?

**Comment by WUJISHANXIA** [comment]
Hi @sebastian-code , i change the func `get_summary` in the class `SummaryHTMLParser(HTMLParser) `.
if there are 30 consecutive non-space characters in the summary, insert a space to the summary.
```
def get_summary(self, suffix=u''):
    count = 0
    index_list = []
    for index, character in enumerate(self.summary):
        if not character.isspace():
            count += 1
        else:
            count = 0
        if count >= 30:
            index_list.append(index)
            count = 0
    summary_list = list(self.summary)
    for index in index_list:
        summary_list.insert(index, u' ')
    self.summary = u''.join(summary_list)
    return u'{0}{1}'.format(self.summary, suffix)
```

it is working properly with really long strings. 
e.g.
long strings
![2017-10-04 9 15 38](https://user-images.githubusercontent.com/13394577/31156330-98e06bc4-a879-11e7-89da-66ffc2cad3f9.png)

articles
![2017-10-04 9 31 43](https://user-images.githubusercontent.com/13394577/31156434-e9ce3cc8-a879-11e7-9fc6-49a8f9fbc817.png)

**Comment by sebastian-code** [comment]
Hi @WUJISHANXIA Nice solution, thanks for that. I still need to consider if this is the best fitting approach for different screen sizes. Shouldn't the UI wrap the text presentation and show it in a more dynamic way, with more responsiveness in front of window size changes? Is that possible?

**Comment by WUJISHANXIA** [comment]
Hi @sebastian-code ，I test it in chrome with different screen sizes，the result are shown below，it can works with different screen sizes . I can't find a simple way to get the screen size  on the server-side.

In addition，can I send a PR for the solution about filtering big image ?

before：
![2017-10-06 1 10 37](https://user-images.githubusercontent.com/13394577/31263875-d1677930-aa2a-11e7-8211-9d99040651f7.png)

after：
1、PC（big screen）  1200px*960px：
![2017-10-06 12 28 28](https://user-images.githubusercontent.com/13394577/31263239-96402018-aa26-11e7-913f-652562c5999b.png)

2、PC （middle screen） 900px*960px：
![2017-10-06 12 41 33](https://user-images.githubusercontent.com/13394577/31263399-92745070-aa27-11e7-8114-a04baa475503.png)


3、PC（small screen） 760px *960px
![2017-10-06 12 41 14](https://user-images.githubusercontent.com/13394577/31263389-8885498e-aa27-11e7-9663-ab5b5d626206.png)

3、mobile phone：
![2017-10-06 12 26 18](https://user-images.githubusercontent.com/13394577/31263044-13ae5ff8-aa25-11e7-8982-2cd23a700f5b.png)

**Comment by sebastian-code** [comment]
To truthful @WUJISHANXIA it looks great, is even better than I think, and I really appreciate the effort you put up to showcase the different outputs. Of course you can send a PR, it will be highly appreciated.

Just a couple of requests on that:

Please, remember to push it against the develop branch.
Don't forget to provide the proper tests for the new code.
This is being aimed to the articles app, but it's useful to the project because there a few apps which use markdown, do you mind to design it with that in mind?

**Comment by sebastian-code** [comment]
Solved.
