### ISSUE TITLE
Infinite scrolling for Feeds

### ISSUE THREAD

**Issue by tritone11** [vitorfs/bootcamp#127]
I see in the README that the infinite scrolling is built in for the Feeds app, but there is no documentation about how to enable it. In the feeds models there is no option to do it. Any clue?

**Comment by sebastian-code** [comment]
To be honest, I don't know, I'll take a look to the code, but in the mean time, if you want to suggest some kind of a fix for it, you're most than welcome.

**Comment by vitorfs** [comment]
The infinite scrolling is activated by default in the homepage and in the user's profile
It shows 10 posts at a time (it can be configured here https://github.com/vitorfs/bootcamp/blob/master/bootcamp/feeds/views.py#L15)

Maybe it's a good idea to move this const to settings.py instead? 

The infinite scrolling is enabled for the feeds app only though, the articles use regular pagination
