### ISSUE TITLE
Is possible moderate the users' activities?

### ISSUE THREAD

**Issue by Allan-Nava** [vitorfs/bootcamp#130]
Hi,

I found [django-moderation](https://github.com/dominno/django-moderation) to moderate the activities of user.

Thanks, best regards

**Comment by sebastian-code** [comment]
This is interesting, it would be useful under a wider scenario than the originally intended for Bootcamp. Do you have than kind of implementation?

**Comment by Allan-Nava** [comment]
At the moment no, but I am developing a custom Bootcamp.

I'm trying to integrate the django-moderation to have a such "parent control" of activities or feeds. 
Furthermore i added groups manager to extend the auth of django.

**Comment by sebastian-code** [comment]
We you have it implemented, and if you're going to share it, please let me know. It sounds interesting.

**Comment by Allan-Nava** [comment]
Where can I find it?

2017-12-06 17:39 GMT+01:00 Sebastian Reyes Espinosa <
notifications@github.com>:
