### ISSUE TITLE
No module named 'django.core.urlresolvers'

### ISSUE THREAD

**Issue by norouzzadeh** [vitorfs/bootcamp#132]
In Django version 2.0, the django.core.urlresolvers module has been moved to django.urls. I get the following error:
ImportError: No module named 'django.core.urlresolvers'

**Comment by sebastian-code** [comment]
The project code base is not yet compatible with Django >= 2.0. That would have to wait a little bit. If you already solved that part, it would be great to include your PR fixing this compatibility issue. Don't forget to follow the collaboration guidelines.

**Comment by gelenaj** [comment]
use this: 

from django.core.urls import reverse

**Comment by ahmed-alhaj1** [comment]
where would include from django.urls import reverse?
like what file?
