### ISSUE TITLE
Is possibile integrate Django-moderation?

### ISSUE THREAD

**Issue by Allan-Nava** [vitorfs/bootcamp#133]
I have found [django-moderation](https://github.com/dominno/django-moderation) but is not working with[ django-guardian](https://github.com/django-guardian)

Also I use [django-groups-manager](https://github.com/vittoriozamboni/django-groups-manager) to handle the groups and users.

**Comment by sebastian-code** [comment]
Hi @Allan-Nava Taking a look at django-moderation, I would say yes, is possible and I don't see it that hard, why you ask?

**Comment by Allan-Nava** [comment]
Hi @sebastian-code, because I got error when I add 'moderation' in **INSTALLED_APPS**

**Comment by sebastian-code** [comment]
What is the error?

**Comment by Allan-Nava** [comment]
My bad I solved
