### ISSUE TITLE
Could you tell me where the "requirements.txt" file is?

### ISSUE THREAD

**Issue by Codevero** [vitorfs/bootcamp#134]
I didn't find this file at the project root. There is only one folder named "requirements" .

**Comment by sebastian-code** [comment]
Hi @Codevero 

The wiki was out of date, I already fixed that, take a look, but to answer directly your question, the requirement files are inside the requirements folder.

For development use the file named `local.txt`, if you are more interested in a production setup, please use `production.txt`.
