### ISSUE TITLE
Command "pythin setup.py egg_info" failed with error code 1 in /tmp/pip-build-eLZ8Xt/Django/

### ISSUE THREAD

**Issue by tarasha** [vitorfs/bootcamp#135]

**Comment by tarasha** [comment]
The requirements.txt file was easy to get through "pip install -U -r requirements.txt", though the installation proceducre has changed, and now when I try to use base.txt, or local.txt or production.txt, it keeps failing with the error-Command "pythin setup.py egg_info" failed with error code 1 in /tmp/pip-build-eLZ8Xt/Django/

**Comment by sebastian-code** [comment]
I haven't been able to reproduce any error when installing requirements; to be of help to you, please, provide additional information, a wider error stack trace (in full if possible), and the steps to reproduce the error.

**Comment by tarasha** [comment]
Thanks for reaching out!

Here’s the stack!

[cid:image001.jpg@01D3734E.ECAB50D0]

**Comment by sebastian-code** [comment]
Sorry, it shows nothing @tarasha, apparently the image was not attached.

**Comment by tarasha** [comment]
Can I get your email address? The issue is the machine where I am running the app and the ubuntu VM; is something I can’t copy the stack due to security controls and RBAC.

Tara

**Comment by sebastian-code** [comment]
Hi @tarasha as you can see, my email address is in my GitHub profile, right below the photo, the email address is sebaslander@gmail.com

**Comment by sebastian-code** [comment]
Hi @tarasha Have you solved your issue through our previous email? If yes, please let me know how you did it, or what was the problem, that should help other people.

**Comment by tarasha** [comment]
Certainly, currently we are testing the platform for RBAC’s; hope to get this resolved soon!

Thanks,
Tara

**Comment by sebastian-code** [comment]
Hi @tarasha did you were able to solve this issue?

**Comment by sebastian-code** [comment]
Closing until there is further development.

**Comment by tarasha** [comment]
Yes I did.

Sent from my iPhone

On Jan 11, 2018, at 2:25 PM, Sebastian Reyes Espinosa <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @tarasha<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftarasha&data=02%7C01%7Ctarasha%40microsoft.com%7C0de1eb329bf74b16005708d5594225da%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636513062996730183&sdata=gU1Gc8di05Cg21iXv0qp86vb4XmkKteCoFM9Jmz%2BeCY%3D&reserved=0> did you were able to solve this issue?

**Comment by mingli91** [comment]
Hey, I have the same issue.
I wonder why you didn't share detailed information...only through private emails
