### ISSUE TITLE
Integrate django-groups-manager and django-guardian

### ISSUE THREAD

**Issue by Allan-Nava** [vitorfs/bootcamp#136]
I think is really comfortable integrate [django-guardian](https://github.com/django-guardian/django-guardian) and [django-groups-manager](https://github.com/vittoriozamboni/django-groups-manager) to handle the permission and groups for bootcamp.

**Comment by sebastian-code** [comment]
Hi @Allan-Nava 

That is great, let me know how it looks when you do it, as with the other features you are implementing on Bootcamp and than we have discussed before.

**Comment by Allan-Nava** [comment]
Hi @sebastian-code ,

I have implemented it !
