### ISSUE TITLE
django-autoslug incompatibility with Django 2.0 

### ISSUE THREAD

**Issue by sebastian-code** [vitorfs/bootcamp#139]
The package `django-autoslug` is currently not in active development, apparently the author has no interest in keep it going. This hinders the possibilities to take update Bootcamp Django version over v1.11.x at this moment.

**Comment by sebastian-code** [comment]
Fixed. Closing it.

**Comment by elsagong** [comment]
Hi Sebastian, may I know how you fix it? I want to use django-autoslug in Django 2.0

**Comment by sebastian-code** [comment]
Sorry, but there is no fix for this that involves that package. It appears than the owner has abandoned the package development making it incompatible with Django>= 2.x, and that is why it has been deprecated from this project.
