### ISSUE TITLE
new method to show the avatar

### ISSUE THREAD

**Issue by teury** [vitorfs/bootcamp#140]
I have seen how the profile image is displayed, and it is not a good technique since the image address is not saved in the DB, but the image is shown according to the user name, but if you change the name of the username, user would lose the image, besides that this method is not compatible with amazonian s3.

imagefield is a better solution or maybe sorl-thumbnail or something similar.

**Comment by sebastian-code** [comment]
I do agree with you @teury but at that moment I haven't been able to replace it in proper way because I do want to keep the specific image loading functionality, but my JS is not really good.

Do you have some PR to propose? That would be nice to have.
