### ISSUE TITLE
GET

### ISSUE THREAD

**Issue by yobra98** [vitorfs/bootcamp#141]
every time i try to send a message i get this error 

please help

GET http://127.0.0.1:8000/messages/check/?_=1516915870607 404 (Not Found)

 and 

POST http://127.0.0.1:8000/messages/send/ 404 (Not Found)

**Comment by sebastian-code** [comment]
@yobra98 this is not enough information, please elaborate around your setup and deployment. Which branch are you trying to run? Are you going for the production of local development setup? Are you running on docker?

Any additional information regardless of your installment and setup process will be helpful.

**Comment by sebastian-code** [comment]
Closing this until there is more information.
