### ISSUE TITLE
Add `on_delete` parameter on all foreign keys

### ISSUE THREAD

**Issue by vitorfs** [vitorfs/bootcamp#142]
This change is required in order to make bootcamp compatible with Django 2.0

PS: If I'm not mistaken, the default behaviour used to be cascade on delete, so I think it would make sense to just add `on_delete=models.CASCADE` to all foreign keys.

Maybe later on we can evaluate the models and check if it would make sense to protect or set null on a few relationships.

**Comment by sebastian-code** [comment]
This has already been added also with the solution for the `reverse` _ImportError_ due to the same version of Django, all of this was done with 1bfb9274dd13f10b5ad44c6d8ecb2a397824da48

**Comment by vitorfs** [comment]
Ah! That's great!
I didn't check the develop branch -- my bad! 😅
