### ISSUE TITLE
Fix UI-UX issues with the notifications

### ISSUE THREAD

**Issue by sebastian-code** [vitorfs/bootcamp#143]
The JS client is a little bit crude at this point, and the notifications workflow needs improvement and refining; right now it needs to solve the next cases:

- An user receives a new notification, if the user reloads the page or changes it to another menu, the styling for the notifications bell changes to its normal status.
- An user receives a new message, if the user reloads the page or changes it to another menu, the styling for the new message notification disappears.
- When a new feed is created, the user who created the new feed receives a notification too.

**Comment by ssahilsahil798** [comment]
I am also working on the notification workflow.

**Comment by ssahilsahil798** [comment]
I am trying to do Fix this UI issue but i am not able to access the related name after changing it from "+". But whatever i do it throws User has no attribute related_name error. I have also tried changing related name from migrations.

**Comment by ssahilsahil798** [comment]
I am fixing this issue already on my project would you like me to collaborate? My Code might have some things that you don't want like i remove the restriction of Related_name on User i.e i am using request.user.notifications.all() for seeing which notifications user has not seen. Also in the code do you change "is_read" to True after sending notification once?

**Comment by sebastian-code** [comment]
Every line of code is welcome. Let's take a look at it. Just remember the [contributing guidelines](https://github.com/vitorfs/bootcamp/blob/master/CONTRIBUTING.md)

**Comment by ssahilsahil798** [comment]
I have added the Friend Feature along with front end. I don't know how to accurately write Unit Tests. I suppose i will first learn Pytest before making a pull request. Since i work only in my free time it might take some time.
