### ISSUE TITLE
The project next phase.

### ISSUE THREAD

**Issue by sebastian-code** [vitorfs/bootcamp#144]
Every mayor library is migrating totally to Python 3 now, even Django starting with v2 will be backwards incompatible with Python 2, django-channels v2 is already tied to Python 3.6 and up because the changes in its implementation.

This new changes to core libraries opens the question not to should we upgrade but to when we will upgrade, as also was established with #66

**Comment by sebastian-code** [comment]
This also begs the question about the Django version, v1.11.x is a LTS version, with support until 2020, and is entirely compatible with Python 2 and also with Django v2.x. So I guess than we need to include it.

**Comment by sebastian-code** [comment]
And at the heart, should this release be backwards compatible with previous Bootcamp state? Perhaps releasing a stable version (v1.x?) and then starting working on a new branch to include all of this upgrades?

**Comment by sebastian-code** [comment]
What do you thing of all of this @vitorfs ?

**Comment by vitorfs** [comment]
I like the idea of releasing a stable 1.x version with python 2 and 3 compatibility
and then we jump to 2.x and make it python 3 only and start using django 2.x with all new features etc

**Comment by sebastian-code** [comment]
Perfect @vitorfs the next logical question is what do you think of the actual state of development of Bootcamp? I thinks is near to be ready to be merged to master and released as v1.x

**Comment by sebastian-code** [comment]
Great, v1.0.1 has been released, Bootcamp v.1 is ready now. So there are some considerations on the project to evaluate how to go from here to Bootcamp v.2:

- Some improvements are in order, not just to keep the code up-to-date, but also to incorporate new versions, new practices and really nice features.
- Some of those improvements could represent a real burden if we have the intention to keep the code backwards compatible with the previous version.
-Some of those changes could imply than there is the risk of not been able to migrate the data.

What do you think of this @vitorfs?

**Comment by sebastian-code** [comment]
Done. Closing.
