### ISSUE TITLE
Upgrade the code base

### ISSUE THREAD

**Issue by sebastian-code** [vitorfs/bootcamp#146]
Given the EOL of Python2, and the end of the support for that version provided by Django, now is a good moment to clean the code and to take advantage of the new nice features offered by Python 3.

**Comment by rashards** [comment]
How are you accounting for the Group module that has been deprecated in channels 2.0?  For example, the following no longer works despite my attempts to update.

models.py

def group_notification(self, activity):
        Group('notifications').send({
                'text': json.dumps({
                'username': self.user.username,
                'activity_type': 'notification',
                'activity': activity

replace with 

from channel.layers import get_channel_layer

def group_notification(self, activity):
          pass_info = json.dumps({
                'username': self.user.username,
                'activity_type': 'notification',
                'activity': activity})
          await self.channel_layer.group_send("notification",pass_info)

**Comment by sebastian-code** [comment]
Hi @rashards. Thanks for your suggestion, I'm aware of the changes introduced to `django-channels` and `asgi_redis`, and given than Bootcamp at this point is still compatible with Python 2, the packages versions are fixed to the ones actually in the files.

**Comment by sebastian-code** [comment]
Closing after fixed in the most recent version release.
