### ISSUE TITLE
Add Social Signup and Login

### ISSUE THREAD

**Issue by bradlishman** [vitorfs/bootcamp#156]
Although referenced in https://github.com/vitorfs/bootcamp/issues/66 and https://github.com/vitorfs/bootcamp/issues/2 this task doesn't seem to have been implemented.

Is it now considered out of scope, or was this just an oversight?

**Comment by sebastian-code** [comment]
Hi @bradlishman It was partially implemented because it requires some additional work if we want to keep it friendly with the old data, and I'm aware than there is still much room for improvement.  We are working on this for the new release.

**Comment by sebastian-code** [comment]
The new version implements an easy way to add this feature, leaving it just to allow some additional setup. Partially solved because this functionality is a little bit out of scope, but with the code base is easy to implement the missing parts.
