### ISSUE TITLE
chat does not work on production server

### ISSUE THREAD

**Issue by ssahilsahil798** [vitorfs/bootcamp#158]
WebSocket connection to 'ws://www.freemediaweb.com/sss/' failed: Error during WebSocket handshake: Unexpected response code: 200

**Comment by sebastian-code** [comment]
Can you provide additional information? this is not useful to determine what is happening in the background, remember than you have to provide the REDIS setup for this to work.

**Comment by ssahilsahil798** [comment]
You website is extremely sophisticated. The problem was resolved though i would love any suggestion of yours if i did something not according to best practices. The deployment on DigitalOcean is tricky, Heroku might be easier and i think you made it for heroku since it contains 'Procfile'. Nginx Config and Daphne config created some problems whose solution i found over internet but not easily. 
1-Created seperate server blocks for Nginx Http and socket requests.
2-Used uWSGI/gunicorn for http and ASGI/Daphne for websockets.
3-Runworker run as a Service so it automatically restarts on crash.
4-Redis with Sudo privileges as a Redis.Service
5-Also i made some changes in Routing.py since Nginx config made me seperate the http and websocket requests or atleast i think so.

I have doubts about this. But this application seems to work beautifully. Also i would like to know that should i run only 1 worker or more??

**Comment by sebastian-code** [comment]
Hi @ssahilsahil798 

Thanks for the comments. You're right, the `.Procfile` is there, but to be honest I don't use Heroku, so I don't pay real attention to it. I do prefer to do a clean deployment, but for those who prefer to use Docker, there is also that foundation.

In the wiki there is only information to help you start and some basics you should not forget, but the deep requirements for this kind of project are beyond the scope and I leave that to the person whoever is going to use it, keep in mind is just another nice Django project and there is a lot of information on that.

To answer your question, that depends on your own technical criteria and your case analysis, perhaps more than one but it should be tied to the user amount, you'll have to measure it and determine which is the best result.

**Comment by ssahilsahil798** [comment]
Though i would like to tell you that you code contains an error. It uses Django 1.6 so you should use from __future__ import unicode_literals in /bootcamp/feeds/views.py. Because you have not used that it throws "UnicodeEncodeError" -Ascii codec can't encode character u'/x04'.

**Comment by sebastian-code** [comment]
For the Django version, please check the requirements files, though it uses Django >= 1.10, and is suggested than it uses Django v1.11.x.

On the other hand, the Unicode Errors surely are because you're using Python2; don't do it, use Python 3 preferably.
