### ISSUE TITLE
delete() not working

### ISSUE THREAD

**Issue by ssahilsahil798** [vitorfs/bootcamp#160]
I made a new Model "UserLoggedIn"

class LoggedInUser(models.Model):
	user = models.OneToOneField(User, related_name='logged_in_user', on_delete=models.CASCADE)

When user log outs i want to delete LoggedInUser instance. But is is not getting deleted. Any dependancies that may prohibit this action.? Any help is appreciated.

**Comment by sebastian-code** [comment]
There is no dependency on that. Perhaps you should consider using signals for that. By the way, have you looked at the notifications workflow on that? There is a workflow implemented to keep track of the user status, perhaps it can be improved but is functional.

**Comment by ssahilsahil798** [comment]
Yes i saw the "user_status" is implemented in the project but i wanted to implement the whole structure myself as this is first time i am working with django-channels and Javascript. Earlier i worked on Andorid apps/java. 
 I added some files to gitignore for separating my local and production settings. Also Javascript Code is written in an unclean fashion.  So i will have to fork another copy of bootcamp and manually do those changes again in a neat and clean way. But before i do this work i am attaching a pic of how the website looks after the changes i made so you can see if you like/want these things in your project. If you think these changes are suitable for your project i would do it and make a pull request.

**Comment by sebastian-code** [comment]
I understand. A couple of observations, you have two ways to achieve what you're trying to do, one is using signals for your model, the other one is to override the `save()` method of your model, to include the functionality you require; about the PR, you're taking your project in a different direction with that style, and we receive PR on bugs, functionalities and other parts of the software, but we want to keep the visual concept; and the last one, please, don't forget to provide the appropriate credits in your forked project, and follow the license guidelines.

**Comment by ssahilsahil798** [comment]
It worked with Signal thanks. i will keep in mind the license guidelines.
