### ISSUE TITLE
ERROR: unsatisfiable constraints:

### ISSUE THREAD

**Issue by mwanjajoel** [vitorfs/bootcamp#169]
This error comes up when trying to run bootcamp in production using docker. 
`openssl-dev-1.0.2o-r0:
    conflicts:
               libressl-dev-2.6.5-r0[pc:libcrypto=1.0.2o]
               libressl-dev-2.6.5-r0[pc:libssl=1.0.2o]
               libressl-dev-2.6.5-r0[pc:openssl=1.0.2o]
    satisfies: world[openssl-dev]
  libressl-dev-2.6.5-r0:
    conflicts:
               openssl-dev-1.0.2o-r0[pc:libcrypto=2.6.5]
               openssl-dev-1.0.2o-r0[pc:libssl=2.6.5]
               openssl-dev-1.0.2o-r0[pc:openssl=2.6.5]
    satisfies:
               postgresql-dev-10.4-r0[libressl-dev]
ERROR: Service 'worker' failed to build: The command '/bin/sh -c apk update   && apk add --virtual build-deps gcc python3-dev musl-dev   && apk add postgresql-dev   && apk add jpeg-dev zlib-dev freetype-dev lcms2-dev openjpeg-dev tiff-dev tk-dev tcl-dev   && apk add libffi-dev openssl-dev py-cffi' returned a non-zero code: 3`

To reproduce the error, clone the repository to a server with Ubuntu 16 LTS, ensure docker and docker-compose are installed and run 
`sudo docker-compose -f production.yml build`

**Comment by sebastian-code** [comment]
It looks like the build issue is related to some dependency constrain related somehow to the basic docker-alpine v3.6 image. I fixed it deleting the clashing dependency and now is building, but I'm not sure is solved. Can you check it out and report back?

**Comment by mwanjajoel** [comment]
Let me try that out and get back to you

**Comment by mwanjajoel** [comment]
Hey @sebastian-code coudl you kindly direct me on which Dockerfile you edited and the steps you took to make the edit?

Also, I edited `openssl-dev` to `openssl`  in the production Dockerfile for postgres and the project is now building very well.

**Comment by sebastian-code** [comment]
I already submitted the required changes into the repo with the last commit, reference in this issue. If you clone the repo you'll have those changes.

**Comment by sebastian-code** [comment]
I have been checking the whole Docker flow, and it appear than there is work to be done due to some django-channels requirements @mwanjajoel
