### ISSUE TITLE
Ask Questions / Write Articles not working!!

### ISSUE THREAD

**Issue by kaustav1996** [vitorfs/bootcamp#173]
Hi, I deployed the lastest version locally following http://cookiecutter-django.readthedocs.io/en/latest/developing-locally.html , signed up , verified email using admin panel and logged in. But when I am trying to write articles / ask Questions this error comes up:

render() got an unexpected keyword argument 'renderer'
Error during template rendering

In template C:\Users\kaust\Desktop\globetrotter\bootcamp\env\lib\site-packages\crispy_forms\templates\bootstrap4\field.html, error at line 28

Any Idea why is this happening? 

![screenshot_2018-08-08 typeerror at articles write-new-article](https://user-images.githubusercontent.com/21956467/43799351-e9ebc968-9aaa-11e8-9e30-a8f91450a670.png)

**Comment by sebastian-code** [comment]
It looks you have a problem with the context variables passed through the _crispy-forms_ package, but you're running this on Windows and I don't use Windows so I can't be of much help. I'm sorry for that.

Can you test it on Linux? Can you test it using the _docker-compose_ scripts? To be honest, running development environments on Windows is hard for almost any software development language, and for Python it makes things even harder.

**Comment by sebastian-code** [comment]
Hi @kaustav1996 do you have updates on this? Have you found something with this issue?

**Comment by kaustav1996** [comment]
Hi @sebastian-code what I did was I removed the renderer argument from the function within crispy-forms in my env. I don't know what damage it will cause in the future.
