### ISSUE TITLE
Deploy on Heroku failing

### ISSUE THREAD

**Issue by kaiofreitas** [vitorfs/bootcamp#177]
Hi!
I've been trying to deploy this application on Heroku.. but I got this error:

`/app/.heroku/python/lib/python3.6/site-packages/environ/environ.py:639: UserWarning: Error reading /app/.env - if you're not configuring your environment separately, check this.
  "environment separately, check this." % env_file)`

I already did all the steps on the cookiecutter docs.
I already ran: heroku config:set DJANGO_SETTINGS_MODULE=config.settings.production

But I'm still getting this error
Appreciate for any help!

**Comment by sebastian-code** [comment]
Hi @kaiofreitas apparently you are missing the `.env` file in the required place.

**Comment by sebastian-code** [comment]
Is there any progress with this issue @kaiofreitas ?
