### ISSUE TITLE
记得以前代码很简单一看就懂，怎么现在变得这么复杂？

### ISSUE THREAD

**Issue by ziming2018** [vitorfs/bootcamp#178]
运行都成问题了

**Comment by sebastian-code** [comment]
Hi @ziming2018 Just english and spanish. Sorry for the inconvenience.

**Comment by ziming2018** [comment]
@sebastian-code How to make it run

**Comment by ziming2018** [comment]
@sebastian-code Too much dependence

**Comment by ziming2018** [comment]
I want to learn django through it.

**Comment by sebastian-code** [comment]
To make it run you please check the Wiki for further information. Is commendable than want to improve your skills with Django, and I'm Honored you want to do it with this project, enjoy it.

About the topic of dependencies, that is subjective, not to me. Perhaps development has some, but that is standard.

**Comment by ziming2018** [comment]
@sebastian-code Ok, thank you
