### ISSUE TITLE
Question, filter messages

### ISSUE THREAD

**Issue by bixicy** [vitorfs/bootcamp#180]
Hi,
is it possible to Filter user in Messages tab? Show only users who received or have received a message

**Comment by sebastian-code** [comment]
Hi @bixicy.

At this moment Bootcamp doesn't has that functionality, but if you want, you can make a PR with that feature.

**Comment by bixicy** [comment]
Sorry, 
but what means PR?

**Comment by bixicy** [comment]
haha, yeah.

I didn't know the acronym.

Is the version running on the test server not yet released?
It differs from the master in some points.

I would be familiarizing myself with the project from about the end of February.

**Comment by sebastian-code** [comment]
Yes @bixicy We use GIT Flow as a method to work on this project and the master branch is what we deem "stable", if you want to contribute, please have in mind [this considerations](https://github.com/vitorfs/bootcamp/wiki/Develop-and-Support).

**Comment by samazaphikel** [comment]
https://github.com/vitorfs/bootcamp/pull/184
