### ISSUE TITLE
error while running locally

### ISSUE THREAD

**Issue by Shekharnunia** [vitorfs/bootcamp#181]
I try to follow [this](https://github.com/vitorfs/bootcamp/wiki/Installing-and-Running-Bootcamp) to test project locally, other than step 5 I perform all the steps but I'm getting these error when I try to post News with the help of modal, can anyone help me to figure out the problem, I really appreciate it.

![selection_003](https://user-images.githubusercontent.com/40422523/51805398-b5ab9000-2292-11e9-8dad-b23667d1002b.png)
![selection_004](https://user-images.githubusercontent.com/40422523/51805399-b6442680-2292-11e9-83bd-db585286dee0.png)

Thanks

**Comment by bixicy** [comment]
I get the same error, I think it's because of the websockets

**Comment by Shekharnunia** [comment]
@sebastian-code please can you help me to understand how do I setup the step 5, I tried but I'm not able to figure out how to solve this issue.
Thanks

**Comment by sebastian-code** [comment]
About the bug, I don't see any on your error logs. About the step five, if you're talking about how to setup Redis, for that I suggest you refer to the manufacturer's instructions, once installed on your system, please change the environment variables as indicated in the wiki.

Keep in mind than that's the reason why I provided the Docker and docker-compose files.

**Comment by Shekharnunia** [comment]
![screenshot from 2019-01-28 16-58-16](https://user-images.githubusercontent.com/40422523/51852091-58bfe080-234b-11e9-980a-8f6f5e7fbbc3.png)

as you can see, when I do upvote it will change colour, and if I do downvote it will stay in previous state and didn't change it.

**Comment by sebastian-code** [comment]
Ah, ok, now I understand, this should be a different issue because is not related with the title nor the original content. Please open than in a new issue to discuss it in it's own context.

**Comment by samazaphikel** [comment]
@Shekharnunia
about Redis. It depends on whether you use Windows or Linux as operating system

Some more details. 
The First steps are only for Windows 10.

1.
Enable Windows Subsystem for Linux.Open **PowerShell as Administrator** 

2.
Run this command
`Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux`
This takes some Minutes, Windows will ask you to reboot your computer when is finish. Yes reboot.

3. 
Open **Microsoft Store** on Windows and search for **Ubuntu 18.04 LTS** and install it.

4.
start Ubuntu
Autosetup for some minutes for the first start. When is finished create your superuser. Then configuration will ask you to create

5.
In Ubuntu Command line, enter the following commands to update the system to the latest version
`sudo apt-get update`
and
`sudo apt-get upgrade`
This command takes some minutes, you have time for a coffee ;-)

------------------
From here it is identical with linux operating system

6.
Intsall redis server in Ubuntu
`sudo apt-get install redis-server`

7.
activate redis command line
`redis-cli -v`

8.
restart redis server
`sudo service redis-server restart`

9. 
testing redis
`redis-cli`


10.
Open your configuration env file from bootcamp. You can user as base `env.example`. At the bottom of the file you have to adjust redis now.

change this line `REDIS_URL=redis://127.0.0.1:6379` to your IP and Port from the console from Ubuntu - redis

11. 
Start your bootcamp server

Finish, have fun

**Comment by Shekharnunia** [comment]
thank you so much for such a great explanation. Now I'm able to easily able to run locally

**Comment by sebastian-code** [comment]
Many thanks to you @samazaphikel for your help to solve @Shekharnunia issue.
