### ISSUE TITLE
bug in vote model 

### ISSUE THREAD

**Issue by Shekharnunia** [vitorfs/bootcamp#183]
![selection_008](https://user-images.githubusercontent.com/40422523/51907631-675ed400-23ed-11e9-9dd9-9de46051c472.png)
In this step, I was testing first upvote then if I immediately do downvote, the vote numbers will change but symbol will not change.
![selection_009](https://user-images.githubusercontent.com/40422523/51907714-a856e880-23ed-11e9-8e2f-116abda05ff3.png)
In this I refresh page and I was having a downvote and I do upvote then the number will change but the symbol will but remain to downvote and new upvote also come
![selection_010](https://user-images.githubusercontent.com/40422523/51907940-4e0a5780-23ee-11e9-9acf-425d545f46f3.png)
and same happen here

**Comment by sebastian-code** [comment]
I see the behavior. To be honest I haven't found this, but perhaps some untested changes on Bootstrap are affecting it. I'll check. Thanks for letting me know @Shekharnunia

**Comment by Shekharnunia** [comment]
I thought you was aware of it, because I noticed it a month ago but didn't put an issue, that's why yesterday first I ask you about this thing

**Comment by samazaphikel** [comment]
I don't think this is a mistake. Please try reloading the pages after you have voted up and down. Possibly even without cache. CTRL + F5.
I think it's related to the django channels. Did you configure Redis correctly?

**Comment by Shekharnunia** [comment]
I don't know if you guys are aware of this but when I search something example 
![selection_013](https://user-images.githubusercontent.com/40422523/51970450-f24ad780-249c-11e9-84cf-0991cec22bda.png) 
let suppose I post this question and then when I type shekhar in search box I get
![selection_011](https://user-images.githubusercontent.com/40422523/51970483-0bec1f00-249d-11e9-8be6-1aef1e734ca2.png)
![selection_012](https://user-images.githubusercontent.com/40422523/51970485-0bec1f00-249d-11e9-9279-598c837b2c00.png)
and this is the same question again and again.
Did you guys make it such a way to work like this?

**Comment by sebastian-code** [comment]
As you said @Shekharnunia the vote UI is not working in the way it was intended. But the bug is not in the model, apparently is in the JS block responsible for doing the animation with the Ajax call, I'll spare some time to check it.

Sorry to be a pain about the search results, that is a new issue to raise, but in a nutshell: no, that's not how it should work, I was able to replicate the results and I have to check it.

**Comment by shekharnunia2** [comment]
> Sorry to be a pain about the search results, that is a new issue to raise, but in a nutshell: no, that's not how it should work, I was able to replicate the results and I have to check it.

actually I was just checking the search app and when I used .distinct() or with example
 ```
context["articles_list"] = Article.objects.filter(Q(
            title__icontains=query) | Q(content__icontains=query) | Q(
                tags__name__icontains=query), status="P").distinct()
```

then I'm getting unique results.
