### ISSUE TITLE
Upvoting our own answer

### ISSUE THREAD

**Issue by maharshi-b** [vitorfs/bootcamp#197]
I can actually able to upvote my own answer. In stackoverflow, they wont allow upvoting our own answers. Can i fix this?

**Comment by sebastian-code** [comment]
Hi @maharshi-b Off course you can try and fix it, I would love to have your PR with a quick fix on this feature. Please remember to keep your local code base up to date and push your PR to develop branch.

**Comment by oma0256** [comment]
Hey @maharshi-b are you working on this or should I take it on?

**Comment by maharshi-b** [comment]
Hi @oma0256 i am beginner to webdev, still learning. i cannot do that now. You can do it. Go..

**Comment by sebastian-code** [comment]
Closing.
