### ISSUE TITLE
Login por redes sociais

### ISSUE THREAD

**Issue by henriquebastos** [vitorfs/bootcamp#2]
Usando o python-social-auth é bem fácil permitir que os usuários associem suas contas do github, facebook ou google accounts p/ logar no site.

Isso poderia facilitar a dinâmica de compartilhamento informações dentro do site além de aumentar a visibilidade p/ novos usuários fora do site.
# sósugestão

@gissues:{"order":99.21875,"status":"notstarted"}

**Comment by sebastian-code** [comment]
This is part of a wider set of functionalities, so I'm closing it now than it has been added to the main set of task on #66
