### ISSUE TITLE
Articles return to created post

### ISSUE THREAD

**Issue by bixicy** [vitorfs/bootcamp#200]
Hi,
https://github.com/vitorfs/bootcamp/blob/master/bootcamp/articles/views.py line 47
`        return reverse('articles:list')`

how is it possible that after success saving it is redirected to the slug url and not to the index?

**Comment by Anand-S23** [comment]
Since `'articles:list'` is what is passed in, it is going to look for that in the urls, and that one corresponds to that is the list of all the articles view. If you want to redirect it to a particular article view right after you submit, you would have to get the slug of the Article.

After you get the slug the reverse would look like: 
`reverse('articles:article', kwargs={'slug':slug})`

The first part is what tells it that you want to go the article detail page, and the second part will give the specific slug of the article.

**Comment by bixicy** [comment]
Yes, but slug is not present in this view
```
class CreateArticleView(LoginRequiredMixin, CreateView):
    """Basic CreateView implementation to create new articles."""
    model = Article
    message = _("Your article has been created.")
    form_class = ArticleForm
    template_name = 'articles/article_create.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, self.message)
        return reverse('articles:list')
```

**Comment by Anand-S23** [comment]
Before the return in the form_valid method, try adding `slug = form.cleaned_data['slug']`. The cleaned data will get the value of slug and store it into slug. You can read more about this here: https://docs.djangoproject.com/en/2.2/ref/forms/validation/#cleaning-a-specific-field-attribute. Now there are several concerns I have with this. One the slug get populated after the form is saved and second that you might not be able to access it form a different method. 

If the first way did not work, I would try `reverse('articles:article', kwargs={'slug':self.object.slug})`. The only other thing I can think of if this doesn't work is changing it to a function based views, as it will easily allow you to do what you are trying, just it is more tedious.

Hope this helps!

**Comment by samazaphikel** [comment]
No, this is not possible. slug is not handled by **form**, by **models**. 

A possible possibility could be to catch the ID after saving and read the slug URL. But I'm not sure if this is the best way. 

Maybe someone else has a better idea

**Comment by sebastian-code** [comment]
Unrelated with the core scope of the application. Closing.
