### ISSUE TITLE
See home screen without being logged

### ISSUE THREAD

**Issue by Vamoss** [vitorfs/bootcamp#201]
Hello,

Is it possible to configure the network to not require signup before using it?
If no, could you point me a way to do that? I would like to help developing this option.

Cheers,
Carlos

**Comment by Anand-S23** [comment]
Hi Carlos,

You have to find the particular view you want people to be able to view without login, and delete the `@login_required` if it is a function based view and the `LoginRequiredMixin` if it is class based views. I don't think this will cause any immediate problems, but it might in the future, just as a warning. 

Hope this helps,
Anand

**Comment by Vamoss** [comment]
It worked, thank you!

**Comment by Vamoss** [comment]
That was how I did it, maybe it would help other people.
https://github.com/EncontrosDigitais/bootcamp/commit/1504d11d121693ff5abf0e421ec8ccbaea4d7b46

It would be wonderful have this optional in the .env file.
