### ISSUE TITLE
Notification is always popping

### ISSUE THREAD

**Issue by Vamoss** [vitorfs/bootcamp#204]
This is happening with translated bootcamp.

This happens because this line it not being translate too:
https://github.com/vitorfs/bootcamp/blob/master/bootcamp/static/js/bootcamp.js#L25

I fixed by doing this:
https://github.com/EncontrosDigitais/bootcamp/commit/0a9eccb6c55f11e0c341f5766b0c48e30ab4b39e

**Comment by sebastian-code** [comment]
Awesome @Vamoss this is a nice workaround. Are you planning to do a PR with it?

**Comment by Vamoss** [comment]
I had to make another repository in my personal account.
The original fixed repository was already to modified 🤦...
