### ISSUE TITLE
Inputs on database design decisions

### ISSUE THREAD

**Issue by saiprashanth173** [vitorfs/bootcamp#208]
Hello folks,

Thanks for developing Bootcamp. 

We are part of the database group at Georgia Tech. We are developing a tool called sqlcheck, for assisting database application developers in designing performant and maintainable applications. sqlcheck automatically detects sub-optimal database design choices and suggests better alternatives. For instance, storing comma-separated values in a column violates the first normal form, which impacts the performance, maintainability, and extensibility of the application.

We extracted SQL queries from Bootcamp and analyzed them with sqlcheck. Here are the results:

**Too many indexes/Indexes not being used:** In certain tables, we observed that the application constructs indexes on many columns or multiple indexes on the same column. Our experiments with sqlcheck showed that constructing too many indexes slows down data ingestion and also increases disk usage. Details are as follows:

- **Notification table:** We see that most of the columns have an index. It’s possible that some of the indexes are not utilized, e.g., column **slug** has two indexes, it’s likely that one of them is redundant.
- **qa_vote table:** We observe that this has 4 different indexes, **1- user_id, content_type_id, object_id,  2- content_type_id,   3- content_type_id, object_id  4- user_id.** We feel that index **3-content_type_id, object_id** is not necessary as in most cases the same performance can be achieved by just using index **1- content_type_id, object_id, user-id.**

We understand that this design decision could stem from application requirements. Could you please share the rationale behind this design decision?

We hope that sqlcheck will assist the broader community of database application developers with designing applications. Your feedback will be greatly appreciated.

Thanks for your time.

**Comment by sebastian-code** [comment]
These choices are delegated to the Django ORM, given the data structure required by the internal workflows. The data relationships in place are due to the way the ORM works for pulling related data.
