### ISSUE TITLE
Help with setting up Apache production

### ISSUE THREAD

**Issue by Vamoss** [vitorfs/bootcamp#209]
Hello,

I've seen this similar support request using nginx (https://github.com/vitorfs/bootcamp/issues/193).

I have a VPS running Ubuntu (18.04) + Apache (2.4.29).
The applications runs well by this command line:
`python3 manage.py runserver 0.0.0.0:8000 --settings=config.settings.production`

Then I configured the WSGI following this tutorial:
https://www.digitalocean.com/community/tutorials/how-to-serve-django-applications-with-apache-and-mod_wsgi-on-ubuntu-14-04

I received a Gateway Timeout, and fixed as recommended by the mod_wsgi author:
https://serverfault.com/a/514251/557436

My apache configuration now look like this:
```Apache
Alias /static /home/my_repository/bootcamp/static
<Directory /home/my_repository/bootcamp/static>
    Require all granted
</Directory>

<Directory /home/my_repository/config>
    <Files wsgi.py>
        Require all granted
    </Files>
</Directory>

WSGIDaemonProcess myproject python-path=/home/my_repository/ python-home=/home/my_repository/myprojectenv
WSGIApplicationGroup %{GLOBAL}
WSGIScriptAlias / /home/my_repository/config/wsgi.py
```

Now I am seeing this error on the Apache.log:
```
mod_wsgi (pid=32745): Target WSGI script '/home/my_repository/config/wsgi.py' cannot be loaded as Python module.
mod_wsgi (pid=32745): Exception occurred processing WSGI script '/home/my_repository/config/wsgi.py'.
Traceback (most recent call last):
  File "/home/my_repository/config/wsgi.py", line 39, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.6/dist-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.6/dist-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/local/lib/python3.6/dist-packages/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.6/dist-packages/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.6/dist-packages/django/conf/__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'config'
```

I hope anyone can help me. I am trying to run bootcamp for almost a month now 😞

Cheers,
Carlos

**Comment by Vamoss** [comment]
I could get a better understanding about wsgi configuration from these documentation:

1. Django wsgi: https://docs.djangoproject.com/en/3.0/howto/deployment/wsgi/
2. Django mod_wsgi: https://docs.djangoproject.com/en/3.0/howto/deployment/wsgi/modwsgi/
3. Django mod_wsgi with virtual enviroment: https://modwsgi.readthedocs.io/en/develop/user-guides/virtual-environments.html

Now my Apache conf look like this:
```Apache
WSGIDaemonProcess myapp python-home=/home/my_repository/myprojectenv

WSGIProcessGroup myapp
WSGIApplicationGroup %{GLOBAL}

WSGIScriptAlias / /home/my_repository/config/wsgi.py

<Directory /home/my_repository/>
    Require all granted
</Directory>
```

The error `ModuleNotFoundError: No module named 'config'` remains...

After running this command:
`python3 manage.py runserver 0.0.0.0:8000`

Without the settings parameters:
`python3 manage.py runserver 0.0.0.0:8000 --settings=config.settings.production`

I was able to get the same error.

So I strongly suspect the problem is related to the envron variables not being defined, specially `DJANGO_SETTINGS_MODULE = 'config.settings.production'`.

I couldn't find a way to initialize the `.env` variables from the wsgi settings.

As bootcamp does not use `settings.py` or the default `wsgi.py` created by Django, I don't know where else to configure these `.env` to startup with wsgi.

**Comment by jinjk92217** [comment]
In you /home/my_repository/config/wsgi.py    
do you have 

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings.production")

before 
application = get_wsgi_application()

**Comment by jinjk92217** [comment]
You can try for example
https://github.com/vitorfs/bootcamp/blob/master/config/wsgi.py#L26
add a line:
sys.path.append(os.path.join(app_path, "/home/my_repository/bootcamp"))

also move line 35 above line 28

**Comment by Vamoss** [comment]
Thank you for helping.
I tried that and the error remains:
`ModuleNotFoundError: No module named 'config'`

I also tried to debug at `wsgi.py`:
```python
print("DJANGO_SETTINGS_MODULE: " + os.environ.get('DJANGO_SETTINGS_MODULE'))
print(os.environ.get('DOMAIN_NAME'))
print("sys.version" + sys.version)
print("path: " + os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
```

And got this:
```
DJANGO_SETTINGS_MODULE: config.settings.production
None
sys.version3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]

path: /home/my_repository
```

And I noticed that the os.environ('DOMAIN_NAME')) was not set.
Should the `.env` file be already loaded?

**Comment by Vamoss** [comment]
The problem was the python working directory.

It was pointing to `/`.

To set the working directory you need to specify the `home` parameter at the `WSGIDaemonProcess`.

My apache conf ended up like this:

```Apache
WSGIDaemonProcess myapp python-home=/home/my_repository/ENV home=/home/my_repository

WSGIProcessGroup myapp
WSGIApplicationGroup %{GLOBAL}

WSGIScriptAlias / /home/my_repository/config/wsgi.py

<Directory /home/my_repository/>
    Require all granted
</Directory>
```

**Comment by Vamoss** [comment]
I have this error when trying to connect to the websocket:
`wss://www.mydomain.com/notifications/`

It returns:
`Error during WebSocket handshake: Unexpected response code: 200`

I am not sure about the issue nature.
How can correctly configure the websocket on a Apache server?

**Comment by sebastian-code** [comment]
@Vamoss Actually there is no need to use Apache, just with the usual setup for Daphne recommended by the people from the Django Channels project is enough. But if you want to use it anyway, the only use you can have for Apache is to use it as a reverse proxy. Perhaps this can help you out https://www.digitalocean.com/community/tutorials/how-to-use-apache-http-server-as-reverse-proxy-using-mod_proxy-extension

**Comment by Vamoss** [comment]
Thank you @sebastian-code !

I was able to run Daphne in parallel with Apache over a differente port:
```
daphne -b 0.0.0.0 -e ssl:port=8090:privateKey=privkey.pem:certKey=cert.pem config.asgi:application
```

Than I changed `window.location.host` in these files:
https://github.com/vitorfs/bootcamp/blob/639687c1422c41d5365335ac4101a42faf6ef767/bootcamp/static/js/bootcamp.js#L94 https://github.com/vitorfs/bootcamp/blob/44b84bd12560029f71d087f64141698567922cd9/bootcamp/static/js/messager.js#L58 https://github.com/vitorfs/bootcamp/blob/65b42e5538712f921ea636894c6f05b9a00897f4/bootcamp/static/js/websocketbridge.js#L275

To this:
```
window.location.hostname + ":8090"
```
