### ISSUE TITLE
ORDER BY not allowed in subqueries of compound statements.

### ISSUE THREAD

**Issue by thesaadmirza** [vitorfs/bootcamp#210]
Just after deploying on local, Open Inbox and getting this error.
Using SQLITE Database.
![Screenshot 2020-02-11 14 55 25](https://user-images.githubusercontent.com/14211943/74226561-94231800-4cde-11ea-9177-773e39bb5a43.png)

**Comment by sebastian-code** [comment]
@thesaadmirza Please check the Wiki and the documentation. Bootcamp doesn't work with SQLite out of the box. If you wish to make it happen, you would need to revamp some parts of the code. Bootcamp is designed to work with PostgreSQL

**Comment by thesaadmirza** [comment]
yeah, I see that. Thanks 
one more thing, the Demo link version, and code is totally different.?

**Comment by sebastian-code** [comment]
Yes @thesaadmirza the demo instance is running an old version.

**Comment by thesaadmirza** [comment]
sorry for asking, where is the old code?
