### ISSUE TITLE
Why do we have a /graphql url?

### ISSUE THREAD

**Issue by Vamoss** [vitorfs/bootcamp#212]
Hi,

I just discorevered a `/graphql` URL, example `www.mydomain/graphql`

This url displays graphql console in the broswer and enables any user the executes queries to retrieve any information from db.

Like user passwords
```
query {
  allUsers {
    id,
    password
  }
}
```

That is a huge security flaw, is there a reason for that?

Cheers,
Carlos

**Comment by sebastian-code** [comment]
Yes @Vamoss the GraphQL API is there to replace any AJAX requirement. The reason you are able to access the server is that it is open to anyone with an valid session. If you want you can disable it, but you need to be careful when doing it not to disable the internal API.

**Comment by Vamoss** [comment]
Thank you again @sebastian-code !

I just commented the line and disabled the access:
https://github.com/vitorfs/bootcamp/blob/44b84bd12560029f71d087f64141698567922cd9/config/urls.py#L24

So far, everything still working.

These are the references I found:
https://github.com/vitorfs/bootcamp/search?q=graphql&unscoped_q=graphql

I will soon test if it break the paginator, not sure how this line works:
https://github.com/vitorfs/bootcamp/blob/d8ce7bfb45829295e231b86f00c90679525badb4/bootcamp/helpers.py#L7
