### ISSUE TITLE
is there any version change

### ISSUE THREAD

**Issue by verkko** [vitorfs/bootcamp#228]
hello all,

I have installed it successfully but am getting the old version (find the screen shot below)

![1](https://user-images.githubusercontent.com/2504880/79338910-ae2ee000-7f45-11ea-9c83-a1062b13e3ad.PNG)

How can i get the latest one as below.

![2](https://user-images.githubusercontent.com/2504880/79338950-be46bf80-7f45-11ea-9e4f-37afc3d9ef8c.PNG)

**Comment by sebastian-code** [comment]
@verkko on which are you working on? This design belongs to the version 1.x.

**Comment by verkko** [comment]
am working on 1st image design. how can i upgrade to the latest

**Comment by sebastian-code** [comment]
Check the branch you're working on @verkko It seems to me that you're on one of the old tags.

**Comment by verkko** [comment]
it is showing *master
