### ISSUE TITLE
Global Interactions count is not working

### ISSUE THREAD

**Issue by verkko** [vitorfs/bootcamp#230]
![1](https://user-images.githubusercontent.com/2504880/79967446-775c4b00-84ac-11ea-8357-6c3cea3ca1c9.PNG)

The Feeds, Articles and all the other counts are not working on my local deployment. Can someone help me on this.

**Comment by Vamoss** [comment]
They are not implemented.
https://github.com/vitorfs/bootcamp/blob/master/bootcamp/templates/users/user_detail.html#L64

**Comment by verkko** [comment]
Can someone help me to that
