### ISSUE TITLE
Email Templates 

### ISSUE THREAD

**Issue by verkko** [vitorfs/bootcamp#232]
How can we change the email templates of verification, forgot password etc.

**Comment by verkko** [comment]
![1](https://user-images.githubusercontent.com/2504880/81302691-4ed17500-9098-11ea-97c7-40420f886f4e.PNG)

**Comment by sebastian-code** [comment]
Yes @verkko you can change them, for that you need to override the templates from Django Allauth, I already modified them a little bit in the folder templates/account, there you can find the ones I override, if need any other one (I think I left a couple intact), just check the documentation, and create your own version.
