### ISSUE TITLE
can we edit the published article?

### ISSUE THREAD

**Issue by xrfinbupt** [vitorfs/bootcamp#27]
from http://trybootcamp.vitorfs.com/articles/
i find can't edit the published article?so,can you add the function?
@gissues:{"order":93.75,"status":"notstarted"}

**Comment by xsurfer** [comment]
Hi, I've noticed that there is no per article authorization mechanism. You can edit articles that belongs to your account (e.g. http://trybootcamp.vitorfs.com/articles/edit/288/ )

**Comment by sebastian-code** [comment]
This is again mentioned on #68. Closing it to keep the issues list clean.
