### ISSUE TITLE
Password reset and username reminder

### ISSUE THREAD

**Issue by jfkw** [vitorfs/bootcamp#32]
I signed up for the demo instance of trybootcamp early on. I can no longer log in due to forgotten username and/or password. I can no longer register with my email address due to the existing user record.

A basic facility to reset password and/or remind of username to configured email address would be helpful.
@gissues:{"order":75,"status":"notstarted"}

**Comment by sebastian-code** [comment]
On this, I would suggest an improvement on the user management implementation going for django-allauth, which implements all those functionalities.

**Comment by sebastian-code** [comment]
Closing it. This issue has been referenced in other issues, also this requirement is part of a broader functionality also mentioned on #53 and #66.
