### ISSUE TITLE
Error: pg_config executable not found. (osx)

### ISSUE THREAD

**Issue by scofier** [vitorfs/bootcamp#34]
pip install -U -r requirements.pip
Error: pg_config executable not found.

Solve: 
brew install postgres --no-tcl
(http://stackoverflow.com/questions/24628567/install-specific-version-of-postgresql-on-mac-using-brew)
@gissues:{"order":50,"status":"notstarted"}

**Comment by vitorfs** [comment]
Usually I solve the problem with

export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/9.3/bin

Anyway I gotta remove postgres as a dependency of the project... I mean, you can run it with any other db Django supports
