### ISSUE TITLE
Migrate django 1.8

### ISSUE THREAD

**Issue by vitorfs** [vitorfs/bootcamp#37]

**Comment by vitorfs** [comment]
ops

**Comment by sidharthshah** [comment]
@vitorfs I've take a first RAW stab at migrating 1.8. Please take a look at my [fork](https://github.com/sidharthshah/bootcamp/tree/master/1.8/bootcamp) Looking at the code I think once we migrate it to 1.8 then we can start making Function Based Views to Class Based Views which would improve the code and make it more current. I'd like to hear you suggestions.

**Comment by vitorfs** [comment]
Good good, I will have a look.
I am planning to put some more effort on its development, and make this project more active. This is a good start.

**Comment by sidharthshah** [comment]
@vitorfs I was thinking of writing some selenium test cases just to double check that migration would not break existing workflows. Do you have a list of workflows that I can take a look at for this?

**Comment by KatherineMichel** [comment]
@sidharthshah The project has been migrated to Django 1.9 now icymi.
