### ISSUE TITLE
webservice endpoint? 

### ISSUE THREAD

**Issue by maxwintko** [vitorfs/bootcamp#40]
Hi 

I am new to Bootcamp and I am thinking to use it in my mobile project. Wondering if bootcamp already have webservice endpoint to communicate with mobile directly? If not i am happy to develop one and contribute. 

Thanks

**Comment by vitorfs** [comment]
Hi Max,

We don't have it at the moment. Perhaps, integrating Bootcamp with [Django REST Framework](http://www.django-rest-framework.org) might solve your problem
