### ISSUE TITLE
Change the asynchronous implementation

### ISSUE THREAD

**Issue by sebastian-code** [vitorfs/bootcamp#47]
Right now the platform uses a loop to monitor changes on activities and notifications, on Django 1.9 you have django channels, created to implement in a better way asynchronous communications.

**Comment by yashLadha** [comment]
I can work upon this @sebastian-code . Can I send a PR for it?

**Comment by yashLadha** [comment]
I am also thinking of django-channels. I thought of making a signals and listener for changes in the database when data is modified into it and trigger a specific user accordingly.

**Comment by sebastian-code** [comment]
Ok, are you planning to use Redis or another messaging queue?

**Comment by yashLadha** [comment]
Redis or celery? I am having confusion? Can you suggest one

**Comment by sebastian-code** [comment]
I apologize for creating it, the two of them cover different purposes, for django-channels would be Redis, but at the end, that doesn't matter, because it should be defined inside the `.env` file, and the code implementation is agnostic of the communication layer, so your approach is just perfect.

**Comment by sebastian-code** [comment]
Solved. Closing
