### ISSUE TITLE
Implementing CBV

### ISSUE THREAD

**Issue by sebastian-code** [vitorfs/bootcamp#50]
This would require a huge amount of work to refactor the code at this level, given the fact than all the views works already smoothly. But this should reduce the amount of actual code and would implement more actual and desirable practices on the project development.

**Comment by anweshknayak** [comment]
anyone working on this ?

**Comment by sebastian-code** [comment]
Hi @anweshknayak Not right now. Are you interested into working on this?

**Comment by anweshknayak** [comment]
@sebastian-code Yes I am. Let me setup this project. I will ask you upon any query

**Comment by sebastian-code** [comment]
Ok @anweshknayak , I would try my best to help.

**Comment by anweshknayak** [comment]
@sebastian-code shall I make a different PR for each app ?

**Comment by sebastian-code** [comment]
Hi @anweshknayak I would think is the best approach.

**Comment by anweshknayak** [comment]
@sebastian-code can you give some hint on what kind of view to use ? ( https://ccbv.co.uk/) I think we can use TemplateView or ListView ?

**Comment by sebastian-code** [comment]
Hi @anweshknayak that would be a list of objects (notifications) so the right approach would be to inherit from ListView, also, don't forget to inherit from the native LogginRequired mixin into the view.

**Comment by tamirOK** [comment]
Is anybody working on this?

**Comment by tamirOK** [comment]
@sebastian-code, do you want every view to be rewritten as cbv?

**Comment by sebastian-code** [comment]
Well, not necessarily @tamirOK CBV are mainly aimed to reduce verbosity and to avoid cases of _DRY_, so I imagine than in some cases it makes more sense to have a functional view, and that requires to apply logic to avoid unnecessary work. I would say than I leave it to you were do you want to give something to the project.

Any help is appreciated.

But don't forget to add test, one of the goals is to improve the coverage percentage.

**Comment by sebastian-code** [comment]
Closing this issue because is to wide and unspecific, which makes it unhelpful. And because is a goal already included in #66 so we can keep up with it there.
