### ISSUE TITLE
about .env config file ?

### ISSUE THREAD

**Issue by Cgruppo** [vitorfs/bootcamp#59]
DEBUG=True
SECRET_KEY='mys3cr3tk3y'
DATABASE_URL='postgres://u_bootcamp:p4ssw0rd@localhost:5432/bootcamp'

localhost database 👍 
postgres://u_bootcamp:p4ssw0rd@localhost:5432/bootcamp'
u_bootcamp:p4ssw0rd  mean database:passwd

**Comment by vitorfs** [comment]
it means: database_user:password@server_url_or_ip:port_number/database_name

**Comment by sebastian-code** [comment]
To clean things up @vitorfs do you mind to close this issue already solved?

**Comment by sebastian-code** [comment]
Closing.
