### ISSUE TITLE
FILE_UPLOAD_PERMISSIONS = 0644 invalid token

### ISSUE THREAD

**Issue by hundhest** [vitorfs/bootcamp#60]
Anyone else encountering this?

**Comment by sebastian-code** [comment]
Perhaps is because the Python version you're implementing on. If you're going with Python3, you need to provide the token on octals format. That way your variable would look like this: `FILE_UPLOAD_PERMISSIONS = 0o644`.

**Comment by hundhest** [comment]
Thanks, that seemed to work. Although now i get the unicode error.. I will try to figure this out. Thanks

**Comment by sebastian-code** [comment]
Try going without the #shebang on the python file.

**Comment by sebastian-code** [comment]
Hi @vitorfs, as other issues I think this one is already solved, i would suggest to close it.

**Comment by sebastian-code** [comment]
Closing
