### ISSUE TITLE
Add functionality to Upvote & Downvote Questions

### ISSUE THREAD

**Issue by sidharthshah** [vitorfs/bootcamp#69]
Right now we do have functionality to up-vote or down-vote Answers in Q&A section. Do you think it would be a good idea to allow users to vote on Questions as well? 

I can take a lead on this feature request if we agree that its worthy to implement this feature.

**Comment by sebastian-code** [comment]
Hi @sidharthshah I think it does. There is always value into giving wider reach to a good question. We certainly will appreciate a lot your help if you're interested.

**Comment by sidharthshah** [comment]
@sebastian-code let me work on this I will submit a PR once I am ready

**Comment by sebastian-code** [comment]
Thanks a lot @sidharthshah

**Comment by arpit1997** [comment]
Is this issue still open for collaboration?

**Comment by sebastian-code** [comment]
Hi @arpit1997, yes, it is; if you have a PR for it, please feel free to submit it.

**Comment by arpit1997** [comment]
I will have a look at it, understand the code and send a PR as soon as I completes it. I hope it does not take much time.

**Comment by sebastian-code** [comment]
Merged de6fc13
