### ISSUE TITLE
Improve UI/UX

### ISSUE THREAD

**Issue by anweshknayak** [vitorfs/bootcamp#72]
Shift to Angular JS or some other JS framework!

**Comment by sebastian-code** [comment]
Well, that depends, why are you considering something like that? Right now there is room for improvement, but still is fine. How do you think than it would be better.

What I'm trying to say is: yes, I do agree but I would like to have a better and deeper conversation about it before thinking into changing the UI, and even more about the UX.

**Comment by teury** [comment]
I think you can change the design. But you can not overload too much, so that the themes can be easily modified by each user, in their different projects.

**Comment by sebastian-code** [comment]
Is this still open for discussion? I'm closing this one until there is further though on it.
