### ISSUE TITLE
tags: strip or replace unsupported delimiters

### ISSUE THREAD

**Issue by unsystemizer** [vitorfs/bootcamp#73]
If I create tags like `a, b, c`, I'll mess up `a` and `b` because they'll have the comma attached to them.

If somebody uses an unsupported delimiter, it could be automatically replaced by the space character.
In that case ` ` and `,` and `;` could all be accepted and that could be indicated in the hint above the tags form field.

**Comment by sebastian-code** [comment]
Thanks @unsystemizer. As I said in my comment on #74 Actually I have been thinking about it, thinking to use Taggit instead. This obviously will fix #74  too. Let work it a little bit more, or, if you have suggestions or perhaps if you submit a PR for this, it will be most appreciated.

**Comment by sebastian-code** [comment]
Solve with 65aabe8e8ffa1ab4ea0ac1441db81fd9d0c4cbc1
