### ISSUE TITLE
tags not searchable

### ISSUE THREAD

**Issue by unsystemizer** [vitorfs/bootcamp#74]
I just tried the demo and couldn't find my question by the tag. 

Maybe that's by design (I noticed there's a tag cloud on the right hand side), but that still makes it hard to find a question or article that uses a popular tag and has some fairly unique word in the body.

For example if I want to find a `python`-tagged question that mentions JavaScript, I'd like to be able to find it by searching for `python javascript` rather than having to browse through all `python`-tagged Q&A, or search for `JavaScript` and find many results unrelated to Python.  
Maybe "search within results" would be useful (so that one can click on a tag and then search all Q&A or articles that contain the tag.)

**Comment by sebastian-code** [comment]
Thanks @unsystemizer. Actually I have been thinking about changing the implementation of tags, and perhaps to use Taggit instead. This obviously will fix #73 too. Let work it a little bit more, or, if you have suggestions or perhaps if you submit a PR for this, it will be most appreciated.

**Comment by unsystemizer** [comment]
Thanks. I would submit a PR if I could but I'm not at that level yet :-)

**Comment by sebastian-code** [comment]
Solve with 65aabe8e8ffa1ab4ea0ac1441db81fd9d0c4cbc1

**Comment by Vamoss** [comment]
Sorry to resurrecting this old issue.

I just installed the latest version and the tags doesn't seem clickable.
All of them points to `href="#"`, and if I try to access the supposed url directly, this gets me a 404 page. Ex: mydomain.com/articles/tag/myTag

Did I missed configuring something? Or is this supposed to happen?

Thank you!
