### ISSUE TITLE
Allow markdown in comments/answers

### ISSUE THREAD

**Issue by unsystemizer** [vitorfs/bootcamp#75]
Some answers may benefit (readability, etc.) from the ability to use enhanced formatting.

At the moment it doesn't seem possible to use markdown in answers and even `\n` is stripped from them, which makes it hard to write complex answers that are easy to read. For example a script or code section in the answer would be very hard to read.

**Comment by sebastian-code** [comment]
I wasn't aware of that, thanks @unsystemizer for pointing that out. Let me check well and then we'll what we can do about it.

**Comment by sebastian-code** [comment]
This was solved with #84. Closing it now.
