### ISSUE TITLE
Admin is not found.

### ISSUE THREAD

**Issue by muhiza** [vitorfs/bootcamp#76]
Why admin side is not there?

**Comment by sebastian-code** [comment]
Hi @muhiza It's the design choice made at the beginning of the project, plus, at the level the project is now, it doesn't require the admin interface mainly because it doesn't provide any functionality to the software... and there is also than there is no admin implementation neither.

**Comment by muhiza** [comment]
It's would be better if there were at least a way the user (admin) can
manage all of those stuffs which are done by the other users.
