### ISSUE TITLE
disk full, cannot register on demo app

### ISSUE THREAD

**Issue by dparizek** [vitorfs/bootcamp#77]
I visit http://trybootcamp.vitorfs.com/ and try to register.  I get error that indicates out of space.

**Comment by sebastian-code** [comment]
I think than @vitorfs is able to work something around this. Perhaps to add some kind of backend than drops the database regularly?

**Comment by vitorfs** [comment]
Aw, I didn't see that one coming 
I will free some space there

**Comment by vitorfs** [comment]
we are back online! sorry for the delay
