### ISSUE TITLE
Password Showing incorrect

### ISSUE THREAD

**Issue by swiftgarg** [vitorfs/bootcamp#80]
conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  password authentication failed for user "u_bootcamp"
FATAL:  password authentication failed for user "u_bootcamp"

**Comment by sebastian-code** [comment]
Hi @swiftgarg Your error indicates than your password is wrong. Did you followed the wiki instructions? Can you provide more information about your database setup and connection configuration?

About the wiki instructions, you can find additional information [here in this link](https://github.com/vitorfs/bootcamp/wiki/Installing-and-Running-Bootcamp)

**Comment by sebastian-code** [comment]
Closing this.
