### ISSUE TITLE
Comment articles

### ISSUE THREAD

**Issue by Agricultures** [vitorfs/bootcamp#81]
When someone write an article, he can easily comment it with writing a comment and pressing Ctrl+Enter. The first comment is publish without problem. To publish a second one, there is a problem : when the user press Crtl+Enter, nothing appends on the web page (but the comment is save in the database). To see the comment in the comment list, the user have to reload manually the web page. 

I'm a beginner, I don't really know how does this project and Github works. I wrote a .po file to traduce the bootcamp app in French. What is the best way to share it ?  Thanks

**Comment by sebastian-code** [comment]
Hi, about the sharing part, if you're talking about including it into the project, the best way to do it is proposing a pull request to the project with your changes and additions. If you want to gain a better understanding of how GitHub works, I suggest to you going into the site [documentatio](https://help.github.com/) were you can find a wide array of useful information.

**Comment by Agricultures** [comment]
Thanks, I'll do it

**Comment by Agricultures** [comment]
I check for the bug on Comment Articles. There is the bug in the version shared on the project and installed in localhost on my laptop, but not in the on line version of victorfs. The problem comes from the code or my configuration ? Thanks

**Comment by sebastian-code** [comment]
Hi @Agricultures is actually a weird problem you're talking about, let me test it by myself, meanwhile why don't you check than the proper bootstraps libraries are being loaded?

**Comment by Agricultures** [comment]
I don't know how to check if the proper bootstraps libraries are being loaded. The web page on my lap top is the same as the on line web page, so I think that there is no problem with the loading of the bootstrap libraries.

**Comment by sebastian-code** [comment]
Is there any new development on this? Closing it until further information is discovered.
