### ISSUE TITLE
 engine = SCHEMES[url.scheme] if engine is None else engine KeyError: ''

### ISSUE THREAD

**Issue by 1500256797** [vitorfs/bootcamp#89]
@rmasoni @shabinesh @lomatus @fabianogoes @vitorfs 

i dont know how to deal with it. i search everywhere,but cant help.can you help me ?  thank you very much.

**This is my .env . file **
`DEBUG=True
SECRET_KEY='ADD_HERE_UR_SECRET_KEY'
DATABASE_URL='sqlite：////Users/vitorfs/Development/bootcamp/db.sqlite3'
ALLOWED_HOSTS = *`

**Comment by sebastian-code** [comment]
Hi @1500256797.

What I see is than you are declaring in a wrong way your database URL, apparently you used the `.env` file added as example, but you didn't update the address properly.

For that I would suggest a small reading of things like [this one](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier) where you can check how the syntax for URi declaration works.

**Comment by 1500256797** [comment]
thanks a lot! it works.
