### ISSUE TITLE
restrict image size

### ISSUE THREAD

**Issue by Humoyun** [vitorfs/bootcamp#92]
I saw several very large images in the site, which is not fit on the screen and looks distracting

**Comment by sebastian-code** [comment]
Hi @Humoyun do you mind to provide more information on this? Knowing more about the issue would be helpful to identify what are you talking about.

On the plus size, you are always welcome to provide a PR to help with the problem.

**Comment by lex-quarkie** [comment]
http://trybootcamp.vitorfs.com/articles/1053-1000x1000-image-is-not-fit-article-preview-window/

Preview with big image looks awful
![preview](https://user-images.githubusercontent.com/4361817/27994210-864cb0a4-64c1-11e7-8d31-d4f41fed9812.png)

If article has big image - Popular tags is stacking over article image,
![tags](https://user-images.githubusercontent.com/4361817/27994226-ce6c363e-64c1-11e7-95e0-90797ddd396f.png)

**Comment by lex-quarkie** [comment]
Actually long text also doesn't fit preview window
![text](https://user-images.githubusercontent.com/4361817/27994288-5e487492-64c3-11e7-9765-abb937b30e50.png)

**Comment by sebastian-code** [comment]
Hi @lex-quarkie @Humoyun I wanted to check something before, do this issue happens just inside the _articles_ app? or does this also happens with other apps?

**Comment by sebastian-code** [comment]
@lex-quarkie @Humoyun Checking this issue, I notice than it happens at markdown creation time. The way it's rendered now makes it a little difficult to filter, even more so to control the outcome, I'll be checking the markdown library implementation to improve the rendering.

**Comment by sebastian-code** [comment]
Hi @lex-quarkie @Humoyun.

I have been checking in depth this topic and I found some workarounds to the requirement like [this one](https://stackoverflow.com/questions/14675913/how-to-change-image-size-markdown/21242579) but that requires to be done at the writing step by the user, and is not working properly; basically this behavior is not mentioned nor supported by the [Syntax Rules](https://daringfireball.net/projects/markdown/syntax) and this feature will not be supported by the package administrator, as described [here](https://github.com/waylan/Python-Markdown/issues/353).

This has no direct solution, do you have another proved approach than does not brake the actual implementation? I will close this issue until there is a better approach.
