### ISSUE TITLE
Crash - "Exception Value:	 need more than 0 values to unpack"

### ISSUE THREAD

**Issue by SeekAndPwn** [vitorfs/bootcamp#96]
The app seems to crash when set up from scratch with 2 users. 
When you go to a profile to one of them (url: http://localhost:8000/testusr/)
you get this nasty crash:

```
Request Method: | GET
-- | --
http://localhost:8000/testusr/
1.11.3
ValueError
need more than 0 values to unpack
Python Executable: | /usr/bin/python
-- | --
2.7.12
Exception Value: | need more than 0 values to unpack
-- | --
```

Any ideas? 

The bug seems to be in this part of code:
```

        query = Activity.objects.filter(user=user).annotate(day=TruncDay(
            'date')).values('day').annotate(c=Count('id')).values('day', 'c')

        dates, datapoints = zip( *[[a['c'], str(a['day'].date())] for a in query])
        return json.dumps(dates), json.dumps(datapoints)
```

It's weird because the other user's profile I created is fine. You can browse it under the profile url without a crash. 

Thanks. It's a nice app btw!

BTW. Is this app a good fit for a production website? To use it as the base. Does it comply with modern standards of django coding etc? :) (excluding SPA of course ;)

**Comment by sebastian-code** [comment]
Hi @SeekAndPwn I haven't been able to reproduce the error you report. I created different amounts of users, superusers from console and registered ones. Up to now it works without an issue. Can you provide to me additional information about your setup and how to reproduce the error?

**Comment by sebastian-code** [comment]
Hi @SeekAndPwn, just when I wrote the previous message, I checked with a different approach, the issue is because the user has no interactions in the portal, so the view crash when it receives a Null value.

I'll work in a solution.

**Comment by sebastian-code** [comment]
@SeekAndPwn I also forgo to answer your question about the quality of the software; its license allows you to check it yourself. I'm pretty confident on the robustness and quality of the software, but I'm also aware than it still has some rough edges. Give it a try if you wish.

**Comment by SeekAndPwn** [comment]
Thanks  for that. I will try to solve this issue too.

**Comment by sebastian-code** [comment]
Solved.
