### ISSUE TITLE
Another crash - on non existent user

### ISSUE THREAD

**Issue by SeekAndPwn** [vitorfs/bootcamp#97]
When you go to URL like this:

http://localhost:8000/j/

where J username is not valid/does not exist. The app doesnt handle it gracefully. It crashes with:

Request Method: | GET
-- | --
http://localhost:8000/j/
1.11.3
DoesNotExist
User matching query does not exist.
/usr/local/lib/python2.7/dist-packages/django/db/models/query.py in get, line 380
/usr/bin/python
2.7.12

**Comment by sebastian-code** [comment]
Solved.
