### ISSUE TITLE
Lack of validation on input from user (GET/POST)

### ISSUE THREAD

**Issue by SeekAndPwn** [vitorfs/bootcamp#99]
It seems like the application does not validate user provided parameters which results in further crashes. 

For example, injecting letter ('f') within last_feed GET parameter:

```
GET /feeds/check/?last_feed=2f2&feed_source=all&_=1500651952280 HTTP/1.1
Host: localhost:8000
```

will result in:
```
Exception Type: ValueError at /feeds/check/
Exception Value: invalid literal for float(): 2f2
```
in this case the problem is the check method of feeds views:

```python
@login_required
@ajax_required
def check(request):
    last_feed  = request.GET.get('last_feed')
```

Here is my patch in case it helps:

```
@login_required
@ajax_required
def check(request):
    last_feed  = request.GET.get('last_feed')
    feeds = Feed.get_feeds_after(last_feed)
    try:
        last_feed  = int(request.GET.get('last_feed'))
        feed_source = int(request.GET.get('feed_source'))
    except ValueError:
        last_feed = 0
        feed_source = 0

    feeds = Feed.get_feeds_after(last_feed)
    if feed_source != 'all':
        feeds = feeds.filter(user__id=feed_source)
    count = feeds.count()
    return HttpResponse(count)
```

I'm catching ValueError. 

Nevertheless there are several other methods that have the same problem.

What's the best solution here? Perhaps adding django's ModelForms validation would help?

**Comment by sebastian-code** [comment]
Hi @SeekAndPwn, thanks for noticing this, to be truthful about your suggestion, I don't know, but I also don't see the need to implement Django ModelForms because the injection is happening on the URL, perhaps it should throw 404 error.

**Comment by sebastian-code** [comment]
Hi again @SeekAndPwn taking a deeper look into it, I noticed something, and is about than this topic is closer to the core concept of error 400, so the proper conversation would be about different error codes handling and how to implement it's management inside a functional view; for the error you're highlighting we can go with perhaps a typical `Http404` error (which would be my choice), `HttpResponseBadRequest` or `SuspiciousOperation`, which could be a more accurate approach.

**Comment by SeekAndPwn** [comment]
Sorry, in my code snippet I had a typo, feed_source should not be casted into an int as it is a string (e.g. feed_source=all).

Or rather , there should an IF clause:
```

    if feed_source != 'all':
       int(request.GET.get('feed_source'))
```

or we could use isdigit()

Regarding the validation. I was also thinking. Maybe it should be done at the url router level?


```
urlpatterns = [
#...
     url(r'^/feeds/check/(?P<last_feed>\d+)/$', 'check', name='check'),
#...
]

```

this way the function check() won't be called without a valid number int the last_feed.

**Comment by hundredrab** [comment]
Hi. I'm new around here, but can I work on this?

**Comment by sebastian-code** [comment]
Of course you can @hundredrab I'll be more than pleased with your help. Please don't forget to check the project [contributing document](https://github.com/vitorfs/bootcamp/blob/master/CONTRIBUTING.md) before submitting any PR.

**Comment by sebastian-code** [comment]
Solved. Code base updated with different approach to some of this use cases.
